### PR TITLE
PoS Block Producer: Txn Timestamps in MsgDeSoBlock

### PR DESCRIPTION
**Pull request by AeonSw4n**

### CODE REVIEW

**Comment by AeonSw4n** [comment]
Current dependencies on/for this PR:
* feature/proof-of-stake
  * **PR #578** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/578" target="_blank">Graphite</a> 
    * **PR #671** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/671" target="_blank">Graphite</a> 
      * **PR #676** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/676" target="_blank">Graphite</a> 
        * **PR #700** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/700" target="_blank">Graphite</a> 
          * **PR #701** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/701" target="_blank">Graphite</a> 
            * **PR #702** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/702" target="_blank">Graphite</a>  👈
        * **PR #689** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/689" target="_blank">Graphite</a> 
      * **PR #673** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/673" target="_blank">Graphite</a> 
      * **PR #672** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/672" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/deso-protocol/core/702?utm_source=stack-comment).

**Comment by tholonious** [comment]
The new RevolutionMetadata as a whole is unused until work on the revolution mechanic is started. Without a full spec for the mechanic, the new metadata type may not account for everything we need to include in the block. There's no rush to build it now.

Please shelf this PR and to revert to the original `TransactionsConnectStatus` field, since it's what we need for now. Once the spec for the new mechanic is fully ready, we can easily introduce a more full fledged revolution metadata for MsgDeSoBlock later.

**Review by tholonious — CHANGES_REQUESTED** [review]
The new `RevolutionMetadata` as a whole is unused until work on the revolution mechanic is started. Without a full spec for the mechanic, the new metadata type may not account for everything we need to include in the block. There's no rush to build it now.

Please shelf this PR and to revert to the original `TransactionsConnectStatus` field, since it's what we need for now. Once the spec for the new mechanic is fully ready, we can easily introduce a more full fledged revolution metadata for `MsgDeSoBlock` later.

**Comment by AeonSw4n** [comment]
Possible naming: Simulated Transaction Timestamps

**Pull request closed without merging**
