### PR TITLE
Update nodes.go

### PR DESCRIPTION
**Pull request by elmasapp**
Adding elmas node to the nodes lists.

### CODE REVIEW

**Review by elmasapp — COMMENTED** [review]
add two node

**Comment by elmasapp** [comment]
@lazynina

**Comment by elmasapp** [comment]
[AeonSw4n](https://github.com/AeonSw4n)
@lazynina

**Comment by elmasapp** [comment]
@AeonSw4n
@lazynina

**Comment by lazynina** [comment]
@elmasapp  - can you please provide some evidence that overclout meets the running for 30 days criteria please? thanks!

**Comment by elmasapp** [comment]
> @elmasapp - can you please provide some evidence that overclout meets the running for 30 days criteria please? thanks!

Github : https://github.com/elmasapp

**Review by lazynina — APPROVED** [review]

**Pull request merged**
